src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $Descripcion = null;

    #[ORM\Column]
    private ?float $Price = null;

    #[ORM\Column(length: 255)]
    private ?string $Imagen = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Categoria $Categoria = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): static
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->Imagen;
    }

    public function setImagen(string $Imagen): static
    {
        $this->Imagen = $Imagen;

        return $this;
    }

    public function getCategoria(): ?Categoria
    {
        return $this->Categoria;
    }

    public function setCategoria(?Categoria $Categoria): static
    {
        $this->Categoria = $Categoria;

        return $this;
    }

    
}

src/Entity/Tienda.php
<?php

namespace App\Entity;

use App\Repository\TiendaRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TiendaRepository::class)]
class Tienda
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\Column(type: "decimal", precision: 10, scale: 7)]
    private ?float $Latitud = null;

    #[ORM\Column(type: "decimal", precision: 10, scale: 7)]
    private ?float $Longitud = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getLatitud(): ?float
    {
        return $this->Latitud;
    }
    
    public function setLatitud(float $Latitud): static
    {
        $this->Latitud = $Latitud;
        return $this;
    }
    
    public function getLongitud(): ?float
    {
        return $this->Longitud;
    }
    
    public function setLongitud(float $Longitud): static
    {
        $this->Longitud = $Longitud;
        return $this;
    }
    
}

templates/detalle/detalle.html.twig
{% extends 'base.html.twig' %}
{% block header %}
{% include 'header.html.twig' %}
{% endblock %}
{% block title %}Menú | Brekky{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/detalle.css') }}?v={{ random() }}" />
{% endblock %}

{% block content %}
<div class="main-content">
    <div class="node--article-header header-product bg-house-green text-white text-center">
        <div class="container">
            <div class="wrapper-header">
                
                
                <div class="product-image">
                    <div class="field field-thumbnail">
                        {% set carpeta = 'bebidas' %}
                        {% if productos.categoria.nombre in ['Porridge', 'Sandwich', 'Focaccia'] %}
                            {% set carpeta = 'comidas' %}
                        {% endif %}

                        {% if productos.imagen %}
                            <img class="imageDetails" src="{{ asset('images/' ~ carpeta ~ '/' ~ productos.imagen) }}" alt="{{ productos.nombre }}" />
                        {% else %}
                            <img class="imageDetails" src="{{ asset('images/default-product.png') }}" alt="Producto sin imagen" />
                        {% endif %}
                    </div>
                </div>

                <!-- Contenedor para el texto (nombre y precio) -->
                <div class="product-info">
                    <div class="product-text">
                        <h1 class="display-xl text-bold">{{ productos.nombre }}</h1>
                    </div>
                    <div class="product-price">
                        <h3 class="display-xl text-bold">${{ productos.price }}</h3>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="node-body-article">
        <div class="container">
            <div class="field-field-product-bio font-paragraph-body">
                <div class="code-paragraph">
                    <p>{{ productos.descripcion }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
{% include 'footer.html.twig' %}
{% endblock %}